### PR TITLE
Update to mpv 0.38.0 command format

### PR DESCRIPTION
**Pull request by AlkyoneAoide**
mpv 0.38.0 now requires an index before options and values for the 'loadfile' command; this PR just implements that change. :)

### CODE REVIEW

**Comment by xi** [comment]
Thanks for the fix! Unfortunately, this does not seem to be backwards compatible. Do you have an idea for a solution that works with both newer and older versions of mpv?

**Comment by AlkyoneAoide** [comment]
Yes!  mpv has built-in seek and pause/resume commands.  If those are used, there's no more need for the `start=xxx` part which is what was breaking on 0.38.0.  I've updated to use mpv's native seek and pause.

**Comment by AlkyoneAoide** [comment]
I did some very quick testing on mpv versions between and including 0.27.2 and 0.38.0, all seem happy.  I can't see anything else functionality-wise to change.

**Comment by xi** [comment]
Thanks for the quick response. Using more mpv features is an interesting approach (cplay traditionally uses a minimal API surface because it used to be a frontend for many different players). However, I fear that this is too big a change for this. For example, I believe it breaks 6880213.

I cherry-picked your initial commit as 3323be6 and added version detection in a87fc6f. The fixed version is available as 3.5.0 on pypi.

If you are interested, i would be very interested to continue this approach in a separate merge request.

**Comment by AlkyoneAoide** [comment]
Thanks for the feedback!  I definitely didn't have the context about cplay (and you're right about this breaking url playing).  I'd also be happy to continue this approach separately, though maybe with some guidance about what exactly that would mean?

**Comment by xi** [comment]
> what exactly that would mean

As I wrote before, cplay currently only uses a very small part of mpv's features. It might be a good idea to use more features. You already experimented with seek and pause, but there are many other areas. For example, we currently do not use any of mpv's playlist features.

For me, there are three potential benefits:

- Reduce complexity in cplay (e.g. if mpv handles playlists, we can remove all playlist parsing code in cplay)
- Improve performance (e.g. if mpv handles playlists, it can already load the next file before the previous one is done)
- Add more features (e.g. mpv might support more playlist formats than cplay currently does)

On the other hand, using more mpv features also means that it becomes harder to switch to a different backend later on. I am also worried that cplay could lose its *character* to a point where it would be easier to just use mpv directly.

I think it is worth experimenting with these ideas, but I would only merge them if the benefits clearly outweigh the drawbacks.

**Pull request closed without merging**
