### PR TITLE
Add -s flag to save/recover state

### PR DESCRIPTION
**Pull request by xi**
This adds a flag `-s`/`--save` that causes cplay to dump its state to a file on close and recover that state on open. The following state is saved:
- playlist
- random
- repeat
- currently played track
- position within track

The state is saved in a file called `.cplay.rec` in the current directory. This means that there is one separate state for each directory.

### CODE REVIEW

**Comment by gotbletu** [comment]
install steps used:
git clone https://github.com/xi/cplay-ng.git
cd cplay-ng
git fetch origin feature-recover
git checkout feature-recover
python cplay/cplay.py

**tested 1: works but doesnt save position**
python cplay/cplay.py
or
python cplay/cplay.py ~/audiobooks/playlist.m3u

This starts up the program just like cplay and can listen to audio no problems. But doesnt seem to save position on exit. Tryed with filelist and adding to playlist mode.

**tested 2: errors fail to load program**
python cplay/cplay.py -s
or
python cplay/cplay.py --save

Traceback (most recent call last):
  File "cplay/cplay.py", line 2154, in <module>
    main()
  File "cplay/cplay.py", line 2063, in main
    args = parse_args()
  File "cplay/cplay.py", line 2048, in parse_args
    recovery = pickle.load(fh)
TypeError: 'str' does not support the buffer interface

---

So this does not work per playlist only per directory? Hope you can fix that, dont like to separate my stuff. 
**playlist.m3u** output the timestamp position to **playlist.m3u.pos** on exit, seems like a good solution.

**Comment by xi** [comment]
> tested 2: errors fail to load program

I will look into that later today.

> So this does not work per playlist only per directory? Hope you can fix that, dont like to separate my stuff. playlist.m3u output the timestamp position to playlist.m3u.pos on exit, seems like a good solution.

Unfortunately it is not that simple. In cplay, the playlist is not bound to any playlist file. Imagine the following scenarion:
1.  cplay is started as `cplay -s playlist.m3u`
2.  After listening for a while, the user clears the playlist and adds some new files in the running cplay
3.  cplay is closed

What should happen in this case? I don't see that saving the state as `playlist.m3u.pos` would be helpful because the playlist in cplay is completely different from `playlist.m3u`.

Another interesting case is if cplay is started without a playlist argument. I would still like to be able to save the state on close, although it is not connected to any playlist whatsoever.

**Comment by xi** [comment]
> > tested 2: errors fail to load program
> 
> I will look into that later today.

Should be fixed in  0af7d06.

**Comment by xi** [comment]
> So this does not work per playlist only per directory?

I now changed it so that you can pass a file to the `-s` option like this:

```
cplay -s playlist.m3u.pos playlist.m3u
```

@gotbletu what do you think?

**Comment by gotbletu** [comment]
Wouldn't it be better to auto detect the **.pos** file, like with an if statement or something. Then you only need to run cplay -s playlist.m3u and if the .pos exist it will just load that also.

**Comment by xi** [comment]
As explained before, that's not possible.

**Comment by gotbletu** [comment]
well if you can't then i guess $cplay -s playlist.m3u.pos playlist.m3u is fine =)

**Comment by xi** [comment]
I just released version 2.1.0 (including this feature) to [pypi](https://pypi.python.org/pypi/cplay-ng/2.1.0)

**Pull request merged**
